### ISSUE TITLE
Display UNL references.

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#589] opened 2023-02-09 01:51 UTC
https://livenet.xrpl.org/network/validators

The list of validators currently displayed in explorer seems to refer to vl.ripple.com.
https://data.xrpl.org/v1/network/validators/main

There is only one validator for ripple in the UNL provided by XRPLF.
https://foundation.xrpl.org/2023/01/25/unl-update-january-2023/

According to the data source (https://data.xrpl.org/v1/network/validators/main) there are two Ripple validators in the UNL provided by ripple.

It could be misleading that XRPLF's blog content differs from the actual UNL if the reference source does not indicate that it is ripple's UNL.

**Comment by ckniffen** [comment] 2023-02-09 01:59
We will investigate this.  It appears the validator-history-service unl information is out of sync.  The validator was also removed from vl.ripple.com but it still shows up in the VHS which is data.xrpl.org too.

**Comment by develoQ** [comment] 2023-02-09 02:06
Even if the UNL provided by XRPLF matches the UNL provided by Ripple, I think the UNL reference source should be indicated to indicate to users that there is not just one UNL in the XRP Ledger, but that multiple entities provide UNLs.

**Comment by ckniffen** [comment] 2023-02-10 01:27
This is the cause of the unl property not being updated. 
Will close this ticket once it deploys and is fixed in prod.  Will then open up another to display info on multiple VL/UNLs.

https://github.com/ripple/validator-history-service/pull/75#pullrequestreview-1292230338

**Comment by ckniffen** [comment] 2023-02-13 19:43
Fixed by https://github.com/ripple/validator-history-service/pull/75#pullrequestreview-1292230338

**Closed by ckniffen** 2023-02-13 19:43 UTC
