### ISSUE TITLE
Undefined values in transaction raw JSON visualization

### ISSUE THREAD

**Issue by zgrguric** [ripple/explorer#452] opened 2022-11-09 09:56 UTC
https://livenet.xrpl.org/transactions/1C480B388ECADC1AED30161F9F50B72B5A5A86894480B3B2B2AFCD056EBF097F/raw

![Screenshot_1](https://user-images.githubusercontent.com/108837406/200799702-417c997e-0dba-4d03-b7c0-5fca96380517.jpg)

**Comment by ckniffen** [comment] 2022-11-09 15:55
Related to #358

**Comment by ckniffen** [comment] 2023-04-12 16:58
Closing as it is a duplicate of #358

**Closed by ckniffen** 2023-04-12 16:58 UTC
